---
exp_arguments:
  n_classes: 2
  save_exp_code: bone_sex_heatmaps_fold0
  raw_save_dir: /data/pathology/projects/lohith/heatmaps/heatmap_raw_results
  production_save_dir: /data/pathology/projects/lohith/heatmaps/heatmap_production_results
  batch_size: 64

data_arguments:
  data_dir: /data/pa_cpgarchive/archives/bone/OsteoVision/public/images
  data_dir_key: source
  process_list: heatmap_fold0.csv
  preset: null
  slide_ext: .mrxs
  label_dict:
    M: 0
    F: 1

patching_arguments:
  patch_size: 224
  overlap: 0.5
  patch_level: 0
  custom_downsample: 1

encoder_arguments:
  model_name: virchow_v2
  target_img_size: 224

model_arguments:
  ckpt_path: /data/pathology/projects/lohith/clam_results/bone_sex_clam_sb_virchow2_s1/s_0_checkpoint.pt
  model_type: clam_sb
  initiate_fn: initiate_model
  model_size: small
  drop_out: 0.25
  embed_dim: 2560

heatmap_arguments:
  vis_level: 2
  alpha: 0.4
  blank_canvas: false
  save_orig: true
  save_ext: jpg
  use_ref_scores: true
  blur: false
  use_center_shift: true
  use_roi: false
  calc_heatmap: true
  binarize: false
  binary_thresh: -1
  custom_downsample: 1
  cmap: coolwarm

sample_arguments:
  samples:
    - name: "topk_high_attention"
      sample: true
      seed: 1
      k: 15
      mode: topk
    - name: "topk_low_attention"
      sample: true
      seed: 1
      k: 15
      mode: reverse_topk
